const IMAGES = {
  ingredients: require("./imageOne.jpg"),
  handDough: require("./FlourHand.jpg"),
  lasagna: require("./lasagna.jpg"),
  spaghetti: require("./spaghetti.jpg"),
  uphuthu: require("./uphuthu.jpg"),
  "Apple and Banana Date Salad": require("./Apple and Banana Date Salad.jpg"),
  "Creamy Pap and Chicken Stew": require("./Creamy Pap and Chicken Stew.jpg"),
  "Curry Scramble": require("./Curry Scramble .jpg"),
  "Fruit Salad with Apricot Dressing": require("./Fruit Salad with Apricot Dressing.jpg"),
  "Grilled Pap and Chicken": require("./Grilled Pap and Chicken.jpg"),
  "Maccaroni and Mince": require("./Maccaroni and Mince.jpg"),
  "Mutton Briyani": require("./Mutton Briyani.jpg"),
  "Pap, chicken and tomato gravy": require("./Pap, chicken and tomato gravy.jpg"),
  "Peri-Peri Chicken Pitas": require("./Peri-Peri Chicken Pitas.jpg"),
  "Potato hand pies": require("./Potato hand pies.jpg"),
  "Rice and Mutton": require("./Rice and Mutton.jpg"),
  "Saucy Bean Baked Eggs": require("./Saucy Bean Baked Eggs.jpg"),
  "Spicy Rice": require("./Spicy Rice.jpg"),
  "Spicy baked beans": require("./Spicy baked beans.jpg"),
  "The chef-style kota": require("./The chef-style kota.jpg"),
  "Tomato & Avocado Sandwiches": require("./Tomato & Avocado Sandwiches.jpg"),
  "Traditional Pap and Chicken": require("./Traditional Pap and Chicken.jpg"),
  "Umngqusho": require("./Umngqusho.jpg"),
  "Uphuthu namasi (dry pap with sour milk)": require("./Uphuthu namasi (dry pap with sour milk).jpg"),
  default: require("./default.jpg"),
  "Chicken Casserole": require("./Chicken Casserole.jpg"),
  "Brinjal curry with chickpea dumplings": require("./Brinjal curry with chickpea dumplings.jpg"),
  "Boerewors stew": require("./Boerewors stew.jpg"),
  "Beens and Greens with Pasta": require("./Beens and Greens with Pasta.jpg"),
  "Balsamic Cucumber Salad": require("./Balsamic Cucumber Salad.jpg"),
  "Apple Salad": require("./Apple Salad.jpg"),
  "Apple Grape Salad": require("./Apple Grape Salad.jpg"),
  "Alphabet soup": require("./Alphabet soup.jpg"),
};

export default IMAGES;
